cargo-features = ["panic-immediate-abort", "profile-rustflags"]

[package]
name = "tinyassist"
version = "0.1.0"
edition = "2024"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "immediate-abort"
rustflags = ["-Zlocation-detail=none", "-Zfmt-debug=none"]
strip = true

[dependencies]
arboard = { version = "3", default-features = false }
argh = "0.1"
colored = "3"
console = "0.16"
directories = "6"
dotenvy = "0.15"
indoc = "2"
minreq = { version = "2", features = ["https-rustls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = "0.27"
strum_macros = "0.27"
thiserror = "2"
