# https://doc.rust-lang.org/cargo/reference/config.html

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["default", "optimize_for_size"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "target-feature=+crt-static"]
